### ISSUE TITLE
try to use it on python3 but having errors

### ISSUE THREAD

**Issue by 6Rebel** [ashishvshenoy/nb-tan-classfiers#1]
Sir,
try to use it on python3 but having errors I will be very thankful you help

Traceback (most recent call last):
  File "C:\Users\acer\Desktop\Learning machine\nb-tan-classfiers-master\bayes.py", line 368, in <module>
    main()
  File "C:\Users\acer\Desktop\Learning machine\nb-tan-classfiers-master\bayes.py", line 364, in main
    tan()
  File "C:\Users\acer\Desktop\Learning machine\nb-tan-classfiers-master\bayes.py", line 293, in tan
    prims()
  File "C:\Users\acer\Desktop\Learning machine\nb-tan-classfiers-master\bayes.py", line 262, in prims
    print (attr.Name+ " " + parent_list[attr.Name].Name+ " "+ attributeList[-1].Name)
KeyError: 'lymphatics'

having this error  please help.

**Comment by beldaz** [comment]
The code uses some Python2 conventions, including `print` without `()` and `dict.has_key()` rather than the Python3 `in` operation. You can see the changes in my pull request https://github.com/ashishvshenoy/nb-tan-classfiers/pull/2 that should make it work.
